// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpwxikjhzzjiypwocjwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwd3hpa2poenpqaXlwd29jandoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjMxODksImV4cCI6MjA2MTQzOTE4OX0.Rx3ni3MwzbWgJl2XzKsXkRV5gycGdl7XWTJ5ah_PWsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);